#
# Sample drill rack file for the enabtmr board.
#
# Drill is the size of the drill bit.
# Min is the smallest hole the bit will be used for.
# Max is the largest hole the bit will be used for.
#
# Each value can have a "unit of measure" added to it,
# such as 0.500mm . If you do not provide the unit of measure,
# values over 0.250 are considered millimeters, and
# values under 0.250 are considered inches. For example:
# 0.400 would be considered 0.400 mm.
# 0.125 would be considered 0.125 inches.
#
# Please note that you must use a TAB character
# between each setting on a line.
# 
# Tip: Set the TAB size of your editor to 12 characters.
#
tool	drill_size	minimum	maximum	length	step	step_z
T01	0.032in	0.001in	0.040in	1.5in
E02	0.032in	0.041in	0.128in	1.5in	0.010in	0.007in
